apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: pipelinerun-helloworld-
  namespace: diploe2-ech
spec:
  serviceAccountName: tekton-sa
  pipelineRef:
    name: pipeline-hello-world
  params:
    - name: your-name
      value: "emmanuelcruz"
    - name: repo-url
      value: https://github.com/EmmanuelCruz/FacturasService.git
  workspaces:
    - name: empty-dir
      emptyDir: {}