apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: buildah-run-
  namespace: diploe2-ech
spec:
  podTemplate:
    securityContext:
      fsGroup: 65532
  taskRef:
    name: buildah
  params:
    - name: IMAGE
      value: 'docker.io/emmanuelcruz/facturas-service:v3.2'
    - name: TLSVERIFY
      value: 'false'
    - name: STORAGE_DRIVER
      value: 'vfs'
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: workspace
    - name: dockerconfig
      secret:
        secretName: dockerconfig-secret