apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: git-clone
  namespace: diploe2-ech
spec:
  taskRef:
    kind: Task
    name: git-clone
  podTemplate:
    securityContext:
      fsGroup: 65532
  params:
  - name: url
    value: "https://github.com/EmmanuelCruz/Modulo5-FacturasService.git"
  - name: deleteExisting
    value: "true"
  workspaces:
  - name: directory
    persistentVolumeClaim:
      claimName: workspace
