apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  namespace: diploe2-ech
  name: pipeline-ci
spec:
  description: |
    This pipeline is used to clone a repository and package the sources in maven:
    Tasks defined in the pipeline:
    - fetch-repository: fetching a git repository as the source
    - maven: package the sources from a maven project, applies the clean and package commands from maven
    - buildah: build an image from a Dockerfile configuration in a maven project and push it into the specified DockerHub account in params
  params:
    - name: repo-url
      type: string
    - name: maven-image
      type: string 
    - name: docker-image
      type: string 
  workspaces:
    - name: workspace
    - name: maven-settings
    - name: dockerconfig-secret
  tasks:
    - name: fetch-repository
      taskRef:
        kind: Task
        name: git-clone
      params:
        - name: url 
          value: $(params.repo-url) 
        - name: deleteExisting
          value: "true"
      workspaces:
        - name: output
          workspace: workspace           
    - name: maven
      taskRef:
        name: maven
      runAfter: 
        - fetch-repository
      params:
        - name: GOALS
          value:
            - -B
            - -DskipTests
            - clean
            - package
        - name: MAVEN_IMAGE
          value: $(params.maven-image)
      workspaces:
        - name: maven-settings
          workspace: maven-settings
        - name: source
          workspace: workspace
    - name: buildah
      taskRef:
          name: buildah
      runAfter:
        - maven
      params:
        - name: IMAGE
          value: $(params.docker-image)
        - name: TLSVERIFY
          value: 'false'
        - name: STORAGE_DRIVER
          value: 'vfs'
      workspaces:
        - name: source
          workspace: workspace
        - name: dockerconfig
          workspace: dockerconfig-secret